export { default as FollowForm } from './FollowForm/index.vue'
export { default as FollowUpDiolog } from './PrivateDetailPop/FollowUpDio.vue'
export { default as SendMessage } from './PrivateDetailPop/SendMessage.vue'
export { default as InfoEditDio } from './PrivateDetailPop/InfoEditDio.vue'
export { default as baseInfoForm } from './CallPhone/BaseInfoForm.vue'
export { default as CallPhone } from './CallPhone/index.vue'
